# Generated by Django 4.0.6 on 2022-08-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='age',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='city',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='country',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
    ]
