# Generated by Django 4.1 on 2022-08-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0003_registration_city_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmpassword',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
