# Generated by Django 4.1 on 2022-08-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0004_registration_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
    ]
