# Generated by Django 4.1 on 2022-08-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0005_remove_registration_city_remove_registration_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='confirmpassword',
            new_name='rpassword',
        ),
    ]
