# Generated by Django 4.1 on 2023-02-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctormodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('hospitalname', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('rate', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
