# Generated by Django 4.1 on 2023-02-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0009_doctormodel_doctor_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='doctor_pic',
        ),
    ]
