# Generated by Django 4.1 on 2023-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0011_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
